# 개인 설정 예시 파일
# 이 파일을 .claude/custom/personal/settings.yaml로 복사하여 사용하세요

# 개발자 정보
developer:
  name: "{{YOUR_NAME}}"
  email: "{{YOUR_EMAIL}}"
  team: "{{YOUR_TEAM}}"
  role: "{{YOUR_ROLE}}"  # backend, frontend, fullstack, devops

# 개인 선호 설정
preferences:
  # 코딩 스타일
  code_style:
    indent: "spaces"  # spaces, tabs
    indent_size: 2    # 2, 4
    line_length: 100  # 80, 100, 120
    quote_style: "single"  # single, double
    
  # 커밋 메시지 스타일
  commit_format: "conventional"  # conventional, simple, detailed
  commit_language: "en"  # en, ko
  
  # 문서 작성 스타일
  documentation:
    language: "ko"  # ko, en, mixed
    detail_level: "medium"  # low, medium, high
    include_examples: true
    
  # 코드 리뷰 스타일
  review_style:
    focus: ["logic", "performance", "readability"]
    comment_style: "constructive"  # direct, constructive, detailed

# 로컬 개발 환경
local_env:
  os: "{{YOUR_OS}}"  # macos, linux, windows
  editor: "{{YOUR_EDITOR}}"  # vscode, vim, intellij, sublime
  terminal: "{{YOUR_TERMINAL}}"
  shell: "{{YOUR_SHELL}}"  # bash, zsh, fish
  
  # 자주 사용하는 도구
  tools:
    - docker
    - kubectl
    - aws-cli
    
# 작업 패턴
work_patterns:
  # 선호하는 작업 시간
  preferred_hours: "09:00-18:00"
  
  # 집중 시간 설정
  focus_blocks:
    - "10:00-12:00"
    - "14:00-16:00"
    
  # 디버깅 스타일
  debug_approach: "systematic"  # systematic, exploratory, minimal

# 프로젝트별 개인 설정
project_overrides:
  "{{PROJECT_NAME}}":
    # 이 프로젝트에서만 사용할 설정
    contexts:
      - "my-project-notes.md"
    shortcuts:
      test: "npm run test:watch"
      build: "npm run build:dev"

# 자동화 설정
automation:
  # 자동 포맷팅
  auto_format: true
  format_on_save: true
  
  # 자동 린팅
  auto_lint: true
  fix_on_save: false
  
  # 커밋 전 검사
  pre_commit_checks:
    - lint
    - format
    - test

# 개인 메모 (선택사항)
notes:
  # 자주 잊어버리는 것들
  reminders:
    - "테스트 먼저 작성하기"
    - "커밋 전 리뷰하기"
    
  # 개선하고 싶은 부분
  improvements:
    - "더 명확한 변수명 사용"
    - "문서화 습관 기르기"