# Clauder 통합 설정 파일
# aliases.yaml과 references.yaml을 통합

# 경로 별칭 정의
aliases:
  # 디렉토리 별칭
  $root: "."
  $claude: ".claude"
  $core: ".claude/templates/core"
  $templates: ".claude/templates"
  $contexts: ".claude/templates/contexts"
  $custom: ".claude/custom"
  $commands: "docs/commands"
  $guides: "docs/guides"
  $hooks: ".claude/hooks"
  $overrides: ".claude/custom/overrides"
  $dev: ".clauder-dev"
  $principles: ".clauder-dev/principles"
  $design: ".clauder-dev/design"
  
  # 파일 별칭 (자주 참조되는 파일)
  $essentials: ".claude/templates/core/01-essentials.template.md"
  $work-principles: ".claude/templates/core/02-work-principles.template.md"
  $dev-principles: ".claude/templates/core/03-dev-principles.template.md"
  $project: ".claude/custom/project.yaml"
  $claude-md: "CLAUDE.md"
  $readme: "README.md"
  $quick-start: "QUICK_START.md"
  
# 참조 매핑 (override 우선순위)
references:
  essentials:
    paths:
      - ".claude/custom/overrides/01-essentials.md"
      - ".claude/templates/core/01-essentials.template.md"
    default: 1  # 0-based index
    
  work-principles:
    paths:
      - ".claude/custom/overrides/02-work-principles.md"
      - ".claude/templates/core/02-work-principles.template.md"
    default: 1
    
  dev-principles:
    paths:
      - ".claude/custom/overrides/03-dev-principles.md"
      - ".claude/templates/core/03-dev-principles.template.md"
    default: 1
    
  contexts:
    paths:
      - ".claude/custom/contexts/"
      - ".claude/templates/contexts/"
    pattern: "*.md"
    
# 특수 참조 (스마트 참조)
smart_references:
  error-handling:
    keywords: ["error", "exception", "bug", "fix"]
    suggest:
      - "docs/guides/troubleshooting.md"
      
  setup:
    keywords: ["install", "setup", "initialize", "start"]
    suggest:
      - "QUICK_START.md"
      - "docs/commands/clauder-start.md"
      - "README.md"
      
  version:
    keywords: ["version", "track", "commit", "update"]
    suggest:
      - "docs/commands/clauder-track.md"
      - ".clauder-dev/design/VERSION_TRACKING.md"

# 시스템 설정
system:
  version_tracking: true
  auto_hooks: true
  strict_mode: false